### ISSUE TITLE
Implement !move command

### ISSUE THREAD

**Issue by coffeepenbit** [terminalnode/mrfreeze#4]
>  look into a !move <ID> #channel command as well, which should take one or more post ID's and move them to #channel.

**Comment by coffeepenbit** [comment]
Working on this ATM

**Comment by coffeepenbit** [comment]
Got it working, just need to clean it up

**Comment by coffeepenbit** [comment]
Right now, broke out a `copy` feature. Will use this within the overarching `move` command, along with a `delete` command to perform a `move`.

**Comment by terminalnode** [comment]
Implemented this today in: https://github.com/terminalnode/mrfreeze/commit/a219d1220b626ed230a166ce20b233f51605aea6

This commit:
- Makes !copy mod only and moves it to the moderation cog.
- Makes copy a helper method and adds an optional boolean delete parameter.
- Has the actual copy-command and newly implemented move-command use this.
- Utilise discord.pys type annotation shenanigans to optionaly allow for multiple messages to be copied/moved with one command.
