### ISSUE TITLE
Implement !disable and !enable commands

### ISSUE THREAD

**Issue by coffeepenbit** [terminalnode/mrfreeze#5]
> an !disable <ID> and !enable <ID> command was being looked into as well, so we could keep beta and non-beta bot in the same servers for the purpose of sourcing emoji.

And possible approach:
> - Use the server settings (config/servers) to save/load the settings, then load them into a dictionary when the bot starts (linking server id to a boolean).
> - Implement a new check for whether the bot is enabled on the server or not, which we'll add to everything except !disable.
> - New cog for the commands themselves.
> - Command should take bot highlight as argument, then verify that it's the bot before doing anything.
channel/role id probably isn't too bad either. basically the same thing as !enable / !disable except without the check

**Comment by terminalnode** [comment]
This has been implemented using the Settings cog's freeze_mutes table. Freeze's self-mute channel is togglable through `!freezemute <bot mention>` (or `!mutefreeze` or `!shutup`... I like aliases).
